!!xyz.relentlesscrew.util.Config
about: 'Relentless Crew is a newly formed Dauntless Guild. We are looking for slayers with diverse backgrounds, time zones, new or experienced that are interested in building a guild/community from the ground up.'
latestAnnouncement: 'Something went wrong'
discordWebhook: https://discordapp.com/api/webhooks/425351971407659029/QXm_mXW_UQh78t3UbO_DXd6cwlSTotQlTIIIJtL8EmTUfzmAZ0RGurkGn35UVOCfd7Jc
discordInvite: https://discord.gg/RghbMp7
